# Generated by Django 2.0.5 on 2019-02-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restLearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text_box',
            field=models.CharField(max_length=1000),
        ),
    ]
